### ISSUE TITLE
Add more bricks

### ISSUE THREAD

**Issue by baba-fish** [BricksVR/bricksvr-issue-tracking#125]
We should add plates (tile-height, studs on top) with the same dimensions as the tiles and bricks.

**Comment by ControllerData** [comment]
lego plates you can place on carpet

**Comment by d12** [comment]
@ControllerData We already have plates. If those aren't what you're thinking, could you send a pic of what you had in mind?

**Comment by ControllerData** [comment]
no really big plate

**Comment by d12** [comment]
Ah I see, yeah we can add some base plates soon :+1:

**Comment by ControllerData** [comment]
> plants

plants, plants plants plants.

**Comment by ControllerData** [comment]
Plants

**Comment by d12** [comment]
Closing in favor of an issue per brick. Please use the "New bricks" template to create brick request issues. https://github.com/BricksVR/bricksvr-issue-tracking/issues/new/choose
