### ISSUE TITLE
Color picker enhancements

### ISSUE THREAD

**Issue by RedGaming98** [BricksVR/bricksvr-issue-tracking#138]
Please note that i'm french and I apologise for errors.

--

The color picker is really cool ngl! But there's some enhancements because there's some small/big things that would be very apreciated and make building easier.

- Common Colors: A color set of a bunch common colors (something like minecraft's 16 base colors) to quickly get into building if you don't really care about having a specific tone of red for example
- Player's recent colors: The game will save like the 20 most recent colors of the player on the client (or server if impossible) or just more color slots (currently there's only 4). Because if you have a project that uses more than 4 colors oh boi you're in trouble
- Room's recent colors: When a player that can build picks a new color it will be added to a menu where everyone can access it and use it. Useful when multiple people build together and want to use the same colors as each other.

--

If confusion emerge because of my bad english or because I can't explain stuff clearly ask me what you don't understand and i will try to explain it better!

**Comment by d12** [comment]
Gonna pull this stuff into #135, thanks!
