### ISSUE TITLE
Destroying builds

### ISSUE THREAD

**Issue by The-Techy** [BricksVR/bricksvr-issue-tracking#140]
**Describe the problem**
From what Nat has shown so far destroying builds with a hammer causes large amounts of lag and reduces the fps dramatically. 

**Describe the solution you'd like**
I think a cool idea could be to have small explosives you could place around the build then detonate later. While these are being placed in the background the game could be figuring out the physics for the explosions, meaning that by the time you set them off, it already knows exactly where each brick will go. There could also be a countdown after hitting the button to set them off that would give it more time to figure out the physics. This way it doesn't have to do realtime physics simulations such as when you throw the hammer at a build, reducing lag significantly. I don't know whether this would be possible, but if it is that would be awesome.

**Comment by d12** [comment]
Gonna pull your comment into #63 , thanks!
