### ISSUE TITLE
Limit Blocks Per Second

### ISSUE THREAD

**Issue by ATXLtheAxolotl** [BricksVR/bricksvr-issue-tracking#149]
Lots of griefers can set their controller keys to a block then spam it to cause lag.

Solution: Limit how many blocks someone can place within a certain amount of time, however do not make it too ridiculous that they practically can’t build

**Comment by d12** [comment]
Yeah, this is a huge pain in public rooms, and it's super easy to implement.

**Comment by d12** [comment]
You can now have a maximum of 10 physics bricks per player
