### ISSUE TITLE
Vignette Effect and Teleport Movement Options to Reduce Motion Sickness

### ISSUE THREAD

**Issue by antillagorilla** [BricksVR/bricksvr-issue-tracking#157]
Moving using the joysticks causes motion sickness. I think adding a settings option (and a slider) for a vignette effect whilst moving would help to alleviate this issue. In other games I have played, that seemed to help quite a bit (first one that comes to mind being Hand Physics Lab I think). Also adding a teleport movement option would be nice and is usually quite common in VR games to have that choice.

**Comment by d12** [comment]
Vignette added in the next version!
