### ISSUE TITLE
Ability to Delete Bricks

### ISSUE THREAD

**Issue by antillagorilla** [BricksVR/bricksvr-issue-tracking#159]
Unless there is something I am missing (in which case it wasn't mentioned in the tutorial), I see no way to delete a brick once it is created. You can throw it on the floor, but then it is just there cluttering up your area and potentially creating lag. Having a dedicated delete button may be beneficial (especially if it is possible to remap those buttons).

**Comment by d12** [comment]
At the moment, there are two ways to delete bricks:

- Push them under the floor, they'll delete themselves after a few seconds
- Leave them on the floor for 5 seconds and they'll despawn

We're removing that second one in the next update though in favor of a maximum number of physics bricks at once, so I agree that we need _something_ to delete bricks. I wouldn't worry too much about the lag though, unattached bricks mainly cause lag when they're all colliding with eachother, bricks scattered on the floor cause almost 0 lag.

**Comment by d12** [comment]
We likely won't add a specific way to delete bricks, since they despawn after 5 seconds.
