### ISSUE TITLE
Blocks don’t disappear when thrown

### ISSUE THREAD

**Issue by SRX-GForce** [BricksVR/bricksvr-issue-tracking#163]
**Describe the bug**
When a block is thrown on 100000, it is likely to fail to disappear.

**To Reproduce**
1. Go to 100000 (that’s the only one that I’ve been in, so it may work in others)
2. Summon a block (it’s happened with a variety of blocks)
3. Throw the block
4. The block will most likely not disappear, despite the fact that it is supposed to do so. 

**Expected behaviour**
The block is supposed to disappear after 5 seconds. 

**Screenshots or video**

**Device information:**
Oculus Quest 2

**Build version:**
v0.2.17

**Additional context**

**Comment by recanman** [comment]
Not a bug.

Recent release:

Version v0.2.17 has been released!

 Changelog:
- Adds 2x1 and 2x2 45° slope bricks
- Adds room names.
  - You're prompted to set a room name when you create a room.
  - If you create a new room via the join menu, you won't be prompted for a name.
  - Old rooms are named "Unnamed Room"
  - Room names display in the "Recent Rooms" menu, and in the in-game room menu.
  - The functionality to change room names will be built in a future update. Message @Nat if you want a room re-named.
- Speed up room load on PCVR by 3x, and on standalone by 20%
**- Unattached bricks are now capped to 10 per player. Spawning more than 10 will despawn your oldest unattached brick. 
- Unattached bricks no longer despawn after 5 seconds**
- Assorted performance improvements and bug fixes.

They don't despawn anymore, rather despawn after having more than 10 attached bricks.
