### ISSUE TITLE
Mechanisms (A.K.A Redstone)

### ISSUE THREAD

**Issue by ChoqueCastroLD** [BricksVR/bricksvr-issue-tracking#164]
I really enjoyed the experience, but I think it needs more, I think it will be a good way of having more fun and expending more time in the game if we have a redstone-like system (Maybe even like the minecraft Create Mod) where we can create complex machines an electrical systems to bring life to our construction

Just imagina building a working train station or a calculator in-game
I think it would be great and I can help with the development if given the chance
Best luck!

**Comment by ATXLtheAxolotl** [comment]
When talking to Nat (head dev) on the build nights he talked about something similar which would be an animate gizmo but still this is a great idea!

**Comment by recanman** [comment]
I had a picture from earlier, its kinda like block scripting.
![image](https://user-images.githubusercontent.com/29310982/117505965-b9322500-af39-11eb-8ad7-04466d2fb554.png)

This would be cool also with a *stop motion mode* or something similar to take pictures and animate it with less of a hassle!

**Comment by ChoqueCastroLD** [comment]
> I had a picture from earlier, its kinda like block scripting.
> ![image](https://user-images.githubusercontent.com/29310982/117505965-b9322500-af39-11eb-8ad7-04466d2fb554.png)
> 
> This would be cool also with a _stop motion mode_ or something similar to take pictures and animate it with less of a hassle!

I think that would break inmersion tho

**Comment by d12** [comment]
Closing as a duplicate issue, I'll pull this info into #54
