### ISSUE TITLE
Bricks that arent placed move when the brick menu touches it

### ISSUE THREAD

**Issue by LuckyK65** [BricksVR/bricksvr-issue-tracking#166]
**Describe the bug**
Bricks that aren't on the floor would move whenever the menu touches them

**To Reproduce**
Spawn a brick and get the brick menu then move the menu with your hand to that brick  and it moves

**Expected behaviour**
Shouldn't move at all

**Device information:**
Rift S

**Build version:**
0.2.19

https://user-images.githubusercontent.com/81326062/117546837-6719fe00-b024-11eb-80e2-078835871e0b.mp4

**Comment by d12** [comment]
Weeeeird. Easy fix, should be fixed soon.

**Comment by d12** [comment]
Fixed in v0.2.21
