### ISSUE TITLE
Blocks duplicating

### ISSUE THREAD

**Issue by WyeHacker** [BricksVR/bricksvr-issue-tracking#168]
**Describe the bug**
A single black block on the build night 5th May server duplicates when grabbed, and then disappears when another is grabbed.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '199999'
2. Grab the single black block seen on the video

**Expected behaviour**
The block to move normally

https://user-images.githubusercontent.com/63447259/117547996-5ec4c180-b02a-11eb-9d72-55d5f543622b.mp4

**Screenshots or Video**
See attached

**Device information:**
Quest 2

**Build version:**
0.2.9

https://user-images.githubusercontent.com/63447259/117547972-4a80c480-b02a-11eb-997f-c02b530145e7.mp4

**Comment by d12** [comment]
Fixed in v0.2.35

**Comment by d12** [comment]
Didn't see this at all in build night. Will close for now :)
