### ISSUE TITLE
Player Collisions

### ISSUE THREAD

**Issue by ATXLtheAxolotl** [BricksVR/bricksvr-issue-tracking#180]
**Describe the problem**
People can fly straight through buildings/walls

**Describe the solution you'd like**
To add collisions to bricks so you can’t walk through them.

**Additional context**
Also a invisible brick/collision could be useful.

**Comment by d12** [comment]
This shouldn't be too much work, and would be pretty fun! I'll likely add it as a room setting, but maybe it could be a player setting at some point.

**Comment by d12** [comment]
Will be added in v0.2.25
