### ISSUE TITLE
Increase refresh rate to 90hz/120hz (from @patrondimitri on Twitter)

### ISSUE THREAD

**Issue by joenash** [BricksVR/bricksvr-issue-tracking#193]
**Describe the problem**
BricksVR currently runs at the original Quest 2 default of 72hz. The Quest 2 is now capable of supporting higher refresh rates. 

**Describe the solution you'd like**
A higher refresh rate version of BricksVR, 90 or 120 hz. 

**Additional context**
Via twitter https://twitter.com/PatronDimitri

**Comment by d12** [comment]
Closing as duplicate of https://github.com/BricksVR/bricksvr-issue-tracking/issues/185
