### ISSUE TITLE
Slope Bricks Missing Features

### ISSUE THREAD

**Issue by RaccKuhnEggs** [BricksVR/bricksvr-issue-tracking#199]
Basically, some code was missed on the slope blocks, making them have fewer features than the other blocks, such as color picker abilities and despawn functions. I know the 1x3 slope has the issue, but I'm not sure about the others.

**To Reproduce**
Steps to reproduce the color-picker behavior:
1. Pull out slope block
2. change the color of the next block
3. try to put it into the color selection menu
4. see error

Steps to reproduce the despawning error:
1. pull out slope block
2. set on the ground without attaching it to anything
3. wait normal despawn time
4. see error

**Expected behavior**
It should despawn after the given time like other blocks, but it doesn't.

**Device information:**
Rift S

**Build version:**
v0.2.23

**Comment by d12** [comment]
Fixed in v0.2.24, thanks for the report!
