### ISSUE TITLE
Customisable tables

### ISSUE THREAD

**Issue by The-Techy** [BricksVR/bricksvr-issue-tracking#204]
**Describe the problem**
Currently there isn't an easy way to save brick colours and quickly access them

**Describe the solution you'd like**
Bring back the tables in the centre of the room, but make them optional, so they can be turned on or off in settings. However, unlike the old tables you should be able to place any brick on it and it will automatically turn it into a brick spawner (ie, when you grab it it spawns a brick in your hand). It could also then place a couple of other bricks of the same colour but different type, like the old ones did with the 2x2, 2x4 and 1x4.

**Additional context**

**Comment by d12** [comment]
Instead of this, I'd like to improve how we spawn bricks from the menu. Maybe we need some sort of "hotbar" or something. I'lll play around with some ideas :)
