### ISSUE TITLE
Sponsor with Chick-fil-a

### ISSUE THREAD

**Issue by ATXLtheAxolotl** [BricksVR/bricksvr-issue-tracking#206]
**Describe the problem**
From a legal standpoint, Chick-fill-a owns the rights to Bob The Cow, which is a problem, how are we supposed to exist without Bob?

**Describe the solution you'd like**
Every day send an email to Chick-Fill-A with The Cow Hair Commercial begging to be sponsored.

**Additional context**
Btw if you do this they may ban you from their stores, idk I’ve never tried something like this before.

**Comment by d12** [comment]
Let's keep GitHub to feature requests and bug reports. You can bug me about this in Discord though :)

**Comment by ATXLtheAxolotl** [comment]
> Let's keep GitHub to feature requests and bug reports. You can bug me about this in Discord though :)

Ur a meanie
