### ISSUE TITLE
Able to walk around main menu.

### ISSUE THREAD

**Issue by ATXLtheAxolotl** [BricksVR/bricksvr-issue-tracking#208]
**Describe the bug**
Players are able to walk around the main menu.

**To Reproduce**
1. Go to 'main menu'
2. Walk to one end of boundary 
3. Use Joystick to rotate boundary to a direction desired.
4. Walk to other side of boundary
5. Repeat.

**Expected behaviour**
I thought that you couldn’t walk around the main menu but you do have the ability to.

**Device information:**
Quest 2

**Build version:**
Latest

**Comment by d12** [comment]
Probably won't fix this since it's not super important.
