### ISSUE TITLE
Brick can be placed on unattached brick and be placed off grid

### ISSUE THREAD

**Issue by perpelator** [BricksVR/bricksvr-issue-tracking#214]
**Describe the bug**
A brick can be placed on unattached brick (only tested with 1x1 on top of a 1x5 or 1x4 forgot which one). No clue if this is a bug or not but I'm assuming it is. 

**To Reproduce**
1. place brick on top of other bricks
2. move brick a little so its still on bricks but not snapped
3. place brick on top
4. observe
Better to understand with attached video.

**Expected behavior**
Top brick shouldn't be able to be placed onto the bottom brick.  

**Screenshots or Video**

https://user-images.githubusercontent.com/57612888/121955016-496f4100-cd14-11eb-8b9e-5cd770eb6de8.mp4

**Device information:**
Quest 2

**Build version:**
v0.2.30

**Comment by d12** [comment]
For now it's intended that you're able to build off-grid, it allows people to build some pretty creative stuff. We might add a setting some day to disable this if people want though.
