### ISSUE TITLE
Version Requirement Option

### ISSUE THREAD

**Issue by ATXLtheAxolotl** [BricksVR/bricksvr-issue-tracking#215]
**Describe the problem**
People could abuse old versions of the games to use old bugs.

**Describe the solution you'd like**
Rooms Owners have the ability to force versions.

**Additional context**
No additional context…

**Comment by d12** [comment]
This is enforced by the game developers. Now that we're in early access, we'll be forcing people to be on the most recent version. You'll see a screen in game telling you to update if you're using an out of date version.
