### ISSUE TITLE
AR Mode

### ISSUE THREAD

**Issue by ATXLtheAxolotl** [BricksVR/bricksvr-issue-tracking#218]
**Describe the problem**
It would be a cool feature if the oculus had an AR mode using its cameras so you could sort of build in your own home.

**Describe the solution you'd like**
Using Oculus’ built in-cameras make an AR Mode.

**Additional context**
No additional context.

**Comment by The-Techy** [comment]
Unfortunately as far I as I know Oculus doesn't allow devs access to the cameras, so I don't think this would work

**Comment by ATXLtheAxolotl** [comment]
Well that’s a shame

**Comment by The-Techy** [comment]
Oculus is now allowing developers access to an experimental API so they can use passthrough, so I think this idea might now be possible. [Link](https://www.theverge.com/2021/7/23/22590794/oculus-mixed-reality-api-quest-2-development-kit-unity)
