### ISSUE TITLE
Ability to choose between dark mode and light mode

### ISSUE THREAD

**Issue by ControllerData** [BricksVR/bricksvr-issue-tracking#219]
**Describe the problem**
I'd like to burn my eyes in BricksVR

**Describe the solution you'd like**
Toggle between dark mode and light mode

**Additional context**
![1_LoAAKCmLu_m5N5HVXbkUOw](https://user-images.githubusercontent.com/29762615/122316349-b38d0f00-cee9-11eb-9352-b7b25debb0e8.gif)

**Comment by d12** [comment]
Duplicate of #59

**Comment by ATXLtheAxolotl** [comment]
> Duplicate of #59

I don’t really think so,
I mean a skybox and different UI modes are different.
