### ISSUE TITLE
Other players can affect your color pickers.

### ISSUE THREAD

**Issue by SaltMKII** [BricksVR/bricksvr-issue-tracking#224]
**Describe the bug**

Other players can change your selected color by passing a brick through the selected color slot in your brick menu.

**To Reproduce**
1. Go to a room with one other person
2. Have them pass a random colored brick through your selected color slot
3. The slot will change to the color of their brick that passed through it

**Expected behavior**
The color pickers should only be able to be changed by the player who opened the menu.

**Screenshots or Video**

https://user-images.githubusercontent.com/83910890/123329324-ae901700-d50a-11eb-85d5-a6d980db07e2.mp4

**Device information:**
Quest 2

**Build version:**
v0.2.30

**Comment by d12** [comment]
Fixed in next version
