### ISSUE TITLE
2x6 tiles (and probably other ones) don't have proper collision

### ISSUE THREAD

**Issue by ControllerData** [BricksVR/bricksvr-issue-tracking#229]
**Describe the bug**
2x6 tiles and probably other tiles can have collision that is not accurate to the actual tile

**To Reproduce**
1. Get a 2x6 tile
2. Put it on something where it has space under it
3. Get any block
4. Make the tile collide with the side of the tile, and it will fall through

**Expected behaviour**
It is supposed to have collisions where it doesn't

**Screenshots or Video**
https://user-images.githubusercontent.com/29762615/123562714-7d1f8180-d77e-11eb-8571-e32dd495fe61.mp4

**Device information:**
Oculus Quest with Link

**Build version:**
v0.2.30

**Additional context**

**Comment by d12** [comment]
Fixed in v0.2.34. The collider was there, but not sized properly.
