### ISSUE TITLE
Frame drops when switching what controller can interact with the menu

### ISSUE THREAD

**Issue by ControllerData** [BricksVR/bricksvr-issue-tracking#230]
**Describe the bug**
The game has a frame drop when you try to switch which controller can interact with the menu
This is amplified when you go on a world with a lot of bricks and it can't get enough FPS to stay smooth, or when it is computing or loading something

**To Reproduce**
1. Go to the menu
2. Switch what hand controls the menu
3. You can see it more clearly when you move your head really fast

**Expected behaviour**
There should be better performance while switching what hand controls the menu

**Screenshots or Video**
https://user-images.githubusercontent.com/29762615/123562962-d340f480-d77f-11eb-8ad6-99e5b6962654.mp4

**Device information:**
Oculus Quest with Link

**Build version:**
v0.2.30

**Additional context**

**Comment by d12** [comment]
Fixed in v0.2.35
