### ISSUE TITLE
Menu Lazer Overlays All

### ISSUE THREAD

**Issue by ATXLtheAxolotl** [BricksVR/bricksvr-issue-tracking#241]
**Describe the bug**
The Lazer used in the menus, overlay all things except the menu.

**To Reproduce**
1. Turn On Headset
2. Open BricksVR
3. Move Cursor Over Bricks In Main Menu

**Expected behaviour**
I would expect the Lazer to disappear when goigg no through a brick but instead is rendered above them. 

**Device information:**
Oculus Quest 2

**Build version:**
v0.2.34

**Additional context**
This bug is small and unimportant but it would make the game a little more polished if fixed.

**Comment by d12** [comment]
It's a little weird, but this is intentional. Without this you wouldn't be able to use the menu when in a closed space (when shrunk and inside of a building)
