### ISSUE TITLE
you can interact with closed Brick Menu

### ISSUE THREAD

**Issue by DaviveCZ** [BricksVR/bricksvr-issue-tracking#258]
**Describe the bug**
You can interact with closed brick menu which makes me mess up multiple times than i should.

**To Reproduce**
1. open the brick menu
2. close it
3. try pressing the grip button in the location it closed at
4. here you go :(

**Expected behaviour**
No interaction with menu at ALL when it's closed

**Device information:**
Oculus Quest 2

**Build version:**
v0.2.37

**Comment by d12** [comment]
Fixed in v0.2.38, thanks for the report!
