### ISSUE TITLE
1x3 slopes dont attach to the top of 1x4 plates

### ISSUE THREAD

**Issue by SaltMKII** [BricksVR/bricksvr-issue-tracking#260]
**Describe the bug**
1x3 slopes don't attach to the top of
 1x4 plates

**To Reproduce**
1. Open BricksVR
2. Grab a 1x3 slope and a 1x4 plate
3. Attempt to attach the slope to the top of the plate

**Expected behaviour**
The slope should attach to the top of the plate.

**Device information:**
Oculus Quest 2

**Build version:**
v0.2.39

**Comment by d12** [comment]
Thanks for the report, this'll be fixed this week :)

**Comment by d12** [comment]
Fixed, this'll be included in the update on Friday.
