### ISSUE TITLE
Export the model as stl/obj minus the world objects

### ISSUE THREAD

**Issue by 0SmooK0** [BricksVR/bricksvr-issue-tracking#50]
**Describe the problem**
Currently, if I create a cool palm tree, I can't have it exported to save it for future appreciation or for the purpose of adding it to the default game map.
We as well as playerbase could use a lot of the models created in the game for presentation, 3D printing or world-building purposes.

**Describe the solution you'd like**
1.) A player has an option to export his creation in a common format (STL/OBJ) - the world objects would not be included,
2.) The exported format would be linked with a relevant data file (XML?) that would have colour information,
3.) The models then could be reused for development purposes of world-building or for personal reasons.

**Note:**
Eventually, I'd also like to see the ability to import the same models but that's more complex and export should be the sart.

**Comment by d12** [comment]
Done!
