### ISSUE TITLE
User shouldn't be able to hold bricks when said brick is not in viewpoint

### ISSUE THREAD

**Issue by recanman** [BricksVR/bricksvr-issue-tracking#83]
**Describe the problem**
 I'm always frustrated when I am accidentally grabbing and I end up holding a brick I was not looking at, then dropping it.

**Describe the solution you'd like**
I would like a check to be implemented before grabbing bricks, if the brick is in the viewport or not.

**Additional context**
Nothing else.

**Comment by d12** [comment]
This is likely not something we'll build as it's a bit un-intuitive. I imagine the friction here is in spawning new bricks, so we'll look into ways to make that a little easier.

**Comment by recanman** [comment]
Ok, thanks for considering!
