### ISSUE TITLE
Customizable bricks

### ISSUE THREAD

**Issue by westereq-dot** [BricksVR/bricksvr-issue-tracking#84]
**Describe the problem**
There are very few bricks variants right now

**Describe the solution you'd like**
So, it is based on 1x1 brick like this in Pic1
And player is able to customize its size by adjusting amount of Pic1 bricks in X and Z axis
example 5x6 brick in Pic2
And 1x2 brick in Pic3

**Additional context**
Pic1
![image](https://user-images.githubusercontent.com/61510763/111876372-afab2880-899e-11eb-9ba3-bc206a117365.png)
Pic2
![image](https://user-images.githubusercontent.com/61510763/111876378-b6d23680-899e-11eb-9bda-06d04f766523.png)
Pic3
![image](https://user-images.githubusercontent.com/61510763/111876386-ba65bd80-899e-11eb-9f07-0dd86d565fd2.png)

**Comment by d12** [comment]
Closing in favor of #56
